# Generated by Django 5.2.8 on 2025-11-16 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نامک')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع مشاوره')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت (تومان)')),
                ('duration', models.PositiveIntegerField(verbose_name='مدت زمان (دقیقه)')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نوع مشاوره',
                'verbose_name_plural': 'انواع مشاوره',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('subject', models.TextField(verbose_name='موضوع')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('admin_response', models.TextField(blank=True, verbose_name='پاسخ مدیر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
            ],
            options={
                'verbose_name': 'پیام تماس',
                'verbose_name_plural': 'پیام\u200cهای تماس',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QACategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نامک')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی پرسش و پاسخ',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای پرسش و پاسخ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='مؤسسه حقوقی دادگان', max_length=200, verbose_name='عنوان سایت')),
                ('site_description', models.TextField(verbose_name='توضیحات سایت')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='لوگو')),
                ('consultation_count', models.PositiveIntegerField(default=1400, verbose_name='تعداد مشاوره')),
                ('success_cases', models.PositiveIntegerField(default=950, verbose_name='پرونده موفق')),
                ('contracts_count', models.PositiveIntegerField(default=500, verbose_name='تنظیم قرارداد')),
                ('experience_years', models.PositiveIntegerField(default=12, verbose_name='سال تجربه')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='عنوان/سمت')),
                ('content', models.TextField(verbose_name='متن نظر')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='امتیاز (1-5)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='تصویر')),
                ('is_published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'نظر مشتری',
                'verbose_name_plural': 'نظرات مشتریان',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک')),
                ('excerpt', models.TextField(max_length=300, verbose_name='خلاصه')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/', verbose_name='تصویر')),
                ('published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawfirm.category', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('field', models.CharField(choices=[('family', 'حقوق خانواده'), ('criminal', 'حقوق کیفری'), ('commercial', 'حقوق تجاری'), ('civil', 'حقوق مدنی'), ('other', 'سایر موارد')], max_length=20, verbose_name='زمینه مشاوره')),
                ('description', models.TextField(verbose_name='توضیح مسئله')),
                ('preferred_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ مطلوب')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('confirmed', 'تأیید شده'), ('completed', 'انجام شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('admin_notes', models.TextField(blank=True, verbose_name='یادداشت مدیر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ درخواست')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('consultation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawfirm.consultationtype', verbose_name='نوع مشاوره')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره',
                'verbose_name_plural': 'درخواست\u200cهای مشاوره',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان سوال')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک')),
                ('content', models.TextField(verbose_name='متن سوال')),
                ('asker_name', models.CharField(max_length=100, verbose_name='نام پرسنده')),
                ('asker_email', models.EmailField(max_length=254, verbose_name='ایمیل پرسنده')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('votes', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('is_answered', models.BooleanField(default=False, verbose_name='پاسخ داده شده')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawfirm.qacategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='متن پاسخ')),
                ('answerer_name', models.CharField(max_length=100, verbose_name='نام پاسخ\u200cدهنده')),
                ('answerer_title', models.CharField(blank=True, max_length=100, verbose_name='عنوان پاسخ\u200cدهنده')),
                ('votes', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('is_best_answer', models.BooleanField(default=False, verbose_name='بهترین پاسخ')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='lawfirm.question', verbose_name='سوال')),
            ],
            options={
                'verbose_name': 'پاسخ',
                'verbose_name_plural': 'پاسخ\u200cها',
                'ordering': ['-is_best_answer', '-votes', 'created_at'],
            },
        ),
    ]
