# Generated by Django 4.2.26 on 2025-12-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawfirm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='seo_description',
            field=models.CharField(blank=True, help_text='توضیحی برای موتور جستجو (حداکثر 160 کاراکتر)', max_length=160, verbose_name='توضیح SEO'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='کلماتی جدا شده با کاما', max_length=255, verbose_name='کلمات کلیدی SEO'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='seo_title',
            field=models.CharField(blank=True, help_text='عنوانی برای موتور جستجو (حداکثر 60 کاراکتر)', max_length=60, verbose_name='عنوان SEO'),
        ),
        migrations.AddField(
            model_name='question',
            name='seo_description',
            field=models.CharField(blank=True, help_text='توضیحی برای موتور جستجو (حداکثر 160 کاراکتر)', max_length=160, verbose_name='توضیح SEO'),
        ),
        migrations.AddField(
            model_name='question',
            name='seo_keywords',
            field=models.CharField(blank=True, help_text='کلماتی جدا شده با کاما', max_length=255, verbose_name='کلمات کلیدی SEO'),
        ),
        migrations.AddField(
            model_name='question',
            name='seo_title',
            field=models.CharField(blank=True, help_text='عنوانی برای موتور جستجو (حداکثر 60 کاراکتر)', max_length=60, verbose_name='عنوان SEO'),
        ),
    ]
