# Generated by Django 4.2.26 on 2025-12-04 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lawfirm', '0002_blogpost_seo_description_blogpost_seo_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='admin_message',
            field=models.TextField(blank=True, verbose_name='پیام مدیر به کاربر'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تعیین شده توسط مدیر'),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('consultation_update', 'به\u200cروز\u200cرسانی مشاوره'), ('consultation_scheduled', 'زمان\u200cبندی مشاوره'), ('consultation_completed', 'اتمام مشاوره'), ('message_response', 'پاسخ به پیام'), ('general', 'اطلاع عمومی')], max_length=30, verbose_name='نوع اطلاع')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lawfirm.consultationrequest', verbose_name='مشاوره مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اطلاع',
                'verbose_name_plural': 'اطلاعات',
                'ordering': ['-created_at'],
            },
        ),
    ]
